''
'' Colors and style for SSI Software Services
'' Based on the mars theme: 
'' https://github.com/future-architect/puml-themes/tree/master/themes
'' Author: Ulrich Luttner
''

' define colors
!$red	= "#CC0033"
!$blue	= "#4FD6E5"
!$dark1	= "#2C2C44"
!$dark2	= "#2B2637"
!$black	= "#080F27"
!$dark	= "#565669"
!$gray	= "#8E99AF"
!$lgray	= "#EDF2F4"
!$lblue	= "#EBF9FF"

' define font
'skinparam defaultFontName RobotoCondensed-Regular
'skinparam defaultFontName IBMPlexSerif
'skinparam defaultFontName Liberation Sans Narrow
'skinparam defaultFontName padmaa-Bold.1.1
skinparam defaultFontName SansSerif

skinparam BackgroundColor $lblue
skinparam shadowing false
skinparam RoundCorner 1
skinparam ArrowColor $black
skinparam FontColor $black
skinparam SequenceLifeLineBorderColor $dark2
skinparam SequenceGroupHeaderFontColor $dark2
skinparam SequenceGroupFontColor $dark
skinparam SequenceGroupBackgroundColor $blue
skinparam SequenceGroupBorderColor $dark
skinparam SequenceGroupBorderThickness 1

skinparam sequenceDivider {
    BorderColor $dark2
    BorderThickness 1.5
    FontColor $dark2
}

skinparam partition {
    BackgroundColor $lgray
    BorderColor $dark2
    FontColor $black
    BorderThickness 1
}

skinparam participant {
    BackgroundColor $red
    BorderColor $dark2
    FontColor FFF
    BorderThickness 1
}

skinparam database {
    BackgroundColor $blue
    BorderColor $dark1
    FontColor $dark2
}

skinparam entity {
    BackgroundColor $gray
    BorderColor $dark2
    FontColor $dark2
}

skinparam note {
    BackgroundColor $gray
    BorderColor $dark2
    FontColor FFF
    BorderThickness 1
}

skinparam actor {
    BackgroundColor $dark2
    BorderColor $dark2
    FontColor $dark2
}

skinparam boundary {
    BackgroundColor $gray
    BorderColor $dark2
    FontColor $dark2
}

skinparam control {
    BackgroundColor $gray
    BorderColor $dark2
    FontColor $dark2
}

skinparam activity {
    BackgroundColor $red
    BorderColor $dark2
    FontColor FFF
}

skinparam collections {
    BackgroundColor $red
    BorderColor $dark2
    FontColor FFF
    BorderThickness 1.5
}

skinparam queue {
    BackgroundColor $red
    BorderColor $dark2
    FontColor FFF
    BorderThickness 1.5
}
